### ISSUE TITLE
issue installing cudatoolkit=11.1  (needed to use conda-forge)

### ISSUE THREAD

**Issue by jonaswagner2826** [BenGravell/spinningup-helper#2]
so idk if this is just me not being an expert with conda, but I did have to figure out a few things to get the correct version of cudatoolkit... It actually worked just fine with 11.0, but I then had to redo it w/ conda-forge to get the correct version. (not sure if anyone else will encounter it, but the fix is simple)

conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia -c conda-forge

ref of similar issue and solutions: https://stackoverflow.com/questions/64589421/packagesnotfounderror-cudatoolkit-11-1-0-when-installing-pytorch

**Comment by BenGravell** [comment]
That might have happened if you did not have conda-forge added to your list of channels beforehand. I forgot to specify that in the guide (it has now been updated with a step to add conda-forge to the channel list). From reading https://docs.conda.io/projects/conda/en/latest/commands/install.html it says
"These are URLs searched in the order they are given (including local directories using the 'file://' syntax or simply a path like '/home/conda/mychan' or '../mychan'). Then, the defaults or channels from .condarc are searched (unless --override-channels is given)." So when I ran the command

conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

conda tried the pytorch channel first, nvidia channel second, then since I had conda-forge on my channel list it checked conda-forge, and indeed my cudatoolkit was installed from the conda-forge channel:

> conda list
&#35; packages in environment at C:\Users\bjgra\anaconda3\envs\spinningup:
&#35;
&#35; Name                    Version                   Build  Channel
cudatoolkit               11.1.1               heb2d755_7    conda-forge

conda-forge is a very common channel so a lot of people just add it to their channel list and forget about it (including me). Thanks for the heads up!
